# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("ashr","assertthat","abind","bigsnpr","GGally","hexbin","mashr","mvtnorm","Rcpp","RcppArmadillo","RcppGSL","rmeta","cluster","cowplot","dplyr","ggplot2","lubridate", "viridis", "magrittr","purrr","readr","rlang","rlist","stats","stringr","tibble","tidyr","tidyselect","testthat","devtools"))'

before_install:
  - sudo apt-get install -y libgsl0-dev
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y libxml2-dev
  - sudo apt-get install -y libssl-dev
  - sudo apt-get install -y libgit2-dev

r_packages:
  - covr

bioc_packages: VariantAnnotation
bioc_packages: GenomicFeatures

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master

