# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages: c("multtest", "GenomicFeatures", "GenomicRanges", "IRanges", "VariantAnnotation")
r_github_packages: privefl/bigsnpr
