# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages: multtest
  VariantAnnotation
r_github_packages: privefl/bigsnpr
  lcolladotor/dots
  stephenslab/mashr@v0.2-11
