# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
bioc_packages: multtest
bioc_packages: VariantAnnotation
r_github_packages: privefl/bigsnpr
r_github_packages: lcolladotor/dots
r_github_packages: stephenslab/mashr@v0.2-11
